// <auto-generated />
using System;
using Hurma.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hurma.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112201014_AddOrdersTable")]
    partial class AddOrdersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hurma.API.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VetId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Hurma.API.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hurma.API.Domain.Entities.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnDuty")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("WorkHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Atatürk Cad. No:45, Merkez, Bilecik",
                            IsOnDuty = true,
                            Latitude = 40.140599999999999,
                            Longitude = 29.979299999999999,
                            Name = "CanVet",
                            Phone = "0228 212 45 67",
                            PhotoUrl = "https://place-puppy.com/400x300",
                            Rating = 4.7999999999999998,
                            WorkHours = "09:00-20:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cumhuriyet Mah. 23. Sk. No:12, Bilecik",
                            IsOnDuty = false,
                            Latitude = 40.142299999999999,
                            Longitude = 29.982500000000002,
                            Name = "Minik Dost Kliniği",
                            Phone = "0228 214 32 10",
                            PhotoUrl = "https://place-puppy.com/401x301",
                            Rating = 4.5999999999999996,
                            WorkHours = "10:00-22:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "İstasyon Cad. No:76, Bilecik",
                            IsOnDuty = false,
                            Latitude = 40.138100000000001,
                            Longitude = 29.984100000000002,
                            Name = "PatiCare Veteriner",
                            Phone = "0228 215 19 20",
                            PhotoUrl = "https://place-puppy.com/402x302",
                            Rating = 4.9000000000000004,
                            WorkHours = "08:30-18:30"
                        });
                });

            modelBuilder.Entity("Hurma.API.Models.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adoptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Golden Retriever",
                            Contact = "@baharaykut",
                            Description = "Sıcakkanlı, oyuncu bir dost arıyor ❤️",
                            Location = "Bilecik Merkez",
                            Name = "Mayki",
                            PhotoUrl = "https://place-puppy.com/300x300",
                            Type = "Köpek"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Van Kedisi",
                            Contact = "0555 555 55 55",
                            Description = "Süt beyaz tüyleriyle minik bir melek 😺",
                            Location = "Bozüyük",
                            Name = "Mırmır",
                            PhotoUrl = "https://placekitten.com/300/300",
                            Type = "Kedi"
                        });
                });

            modelBuilder.Entity("Hurma.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kedi Ürünleri",
                            Description = "Yüksek proteinli tavuklu kuru kedi maması.",
                            Name = "Reflex Kedi Maması",
                            PhotoUrl = "https://placekitten.com/400/400",
                            Price = 229.90m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Köpek Ürünleri",
                            Description = "Yetişkin köpekler için vitaminli kuru mama.",
                            Name = "Bonacibo Köpek Maması",
                            PhotoUrl = "https://place-puppy.com/400x400",
                            Price = 349.90m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Kuş Ürünleri",
                            Description = "Orta boy, sağlam metal kuş kafesi.",
                            Name = "Kuş Kafesi",
                            PhotoUrl = "https://placebear.com/400/400",
                            Price = 599.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Aksesuar",
                            Description = "3 parçadan oluşan interaktif kedi oyuncağı.",
                            Name = "Kedi Oyuncağı Seti",
                            PhotoUrl = "https://placekitten.com/401/401",
                            Price = 129.50m
                        });
                });

            modelBuilder.Entity("Hurma.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hurma.API.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Hurma.API.Domain.Entities.Vet", "Vet")
                        .WithMany()
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vet");
                });
#pragma warning restore 612, 618
        }
    }
}
